sonar.projectKey=AYANOKOJI-71_devsecops-cicd-platform
sonar.organization=ayanokoji-71
sonar.projectName=DevSecOps CI/CD Platform
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.exclusions=**/__pycache__/**
