apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: delivery-api
  namespace: devsecops-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: delivery-api
