apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: delivery-api-deployer
  namespace: devsecops-platform
subjects:
  - kind: Group
    name: devsecops-deployers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: delivery-api-deployer
  apiGroup: rbac.authorization.k8s.io
