apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: delivery-api-deployer
  namespace: devsecops-platform
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["delivery-api"]
    verbs: ["get", "watch", "patch"]
